
--- SEED TurbineTypes and Turbines

INSERT INTO [WIND-POWER-SYSTEM].[dbo].[TurbineTypes] VALUES ('Vestas', 'V39/600', 600);
INSERT INTO [WIND-POWER-SYSTEM].[dbo].[TurbineTypes] VALUES ('Siemens Gamesa', 'SG 2.1-114', 1140);
INSERT INTO [WIND-POWER-SYSTEM].[dbo].[TurbineTypes] VALUES ('Nordex', 'N43', 800);
INSERT INTO [WIND-POWER-SYSTEM].[dbo].[TurbineTypes] VALUES ('Enercon', 'E-44', 900);

INSERT INTO [WIND-POWER-SYSTEM].[dbo].[Turbines] VALUES ('V52/850/2014-dk/kol-863', 'Installed', 1);
INSERT INTO [WIND-POWER-SYSTEM].[dbo].[Turbines] VALUES ('SG2.1-114/2013-dk/kol-605', 'Installed', 2);
INSERT INTO [WIND-POWER-SYSTEM].[dbo].[Turbines] VALUES ('N43/2011-dk/kol-536', 'Run', 3);
INSERT INTO [WIND-POWER-SYSTEM].[dbo].[Turbines] VALUES ('E-44/2016-dk/kol-221', 'ReadyNoWind', 4);

-- Generate and insert 10,000 turbines with specific naming patterns (autogenerated by AI)
DECLARE @counter INT = 1;

WHILE @counter <= 10000
BEGIN
    INSERT INTO [WIND-POWER-SYSTEM].[dbo].[Turbines] (SerialNumber, Status, TurbineTypeId)
    VALUES (
        CONCAT(
            CASE 
                WHEN (@counter % 4) + 1 = 1 THEN 'V52/850/2014-dk/kol-'
                WHEN (@counter % 4) + 1 = 2 THEN 'SG2.1-114/2013-dk/kol-'
                WHEN (@counter % 4) + 1 = 3 THEN 'N43/2011-dk/kol-'
                WHEN (@counter % 4) + 1 = 4 THEN 'E-44/2016-dk/kol-'
            END,
            @counter
        ), -- Generate unique SerialNumber based on type and counter
        CASE 
            WHEN @counter % 5 = 1 THEN 'Installed'
            WHEN @counter % 5 = 2 THEN 'Run'
            WHEN @counter % 5 = 3 THEN 'InService'
            WHEN @counter % 5 = 4 THEN 'ReadyNoWind'
            ELSE 'Failed'
        END, -- Assign Status cyclically
        (@counter % 4) + 1 -- Assign TurbineTypeId cyclically (1 to 4)
    );

    SET @counter = @counter + 1;
END;

select * from  [dbo].[TurbineTypes]
select * from  [dbo].[Turbines]